import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import type { IssueCategory, LensReport } from '@origami/contracts';
import { CATEGORY_LABEL, fetchSharedReport, ApiRequestError } from '../api/client';
import { OrigamiLensIcon } from '../components/icons';
import { AnimatedScoreRing } from '../components/AnimatedScoreRing';
import { AnimatedProgressBar } from '../components/AnimatedProgressBar';

type ViewState = 'loading' | 'not-found' | 'ready' | 'error';

function hostnameOf(url: string): string {
  try {
    return new URL(url).hostname;
  } catch {
    return url;
  }
}

const SEVERITY_TONE: Record<string, string> = { CRITICAL: 'critical', HIGH: 'high', MEDIUM: 'medium', LOW: 'low' };

function IssueCard({ issue }: { issue: LensReport['issues'][number] }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="shared-report-issue-card">
      <button type="button" className="shared-report-issue-header" onClick={() => setOpen((o) => !o)} aria-expanded={open}>
        <span className={`severity-badge ${SEVERITY_TONE[issue.severity] ?? 'low'}`}>{issue.severity}</span>
        <span className="shared-report-issue-title">{issue.title}</span>
        <span className="shared-report-issue-category">{CATEGORY_LABEL[issue.category]}</span>
        <span className="shared-report-issue-chevron" aria-hidden="true">{open ? '−' : '+'}</span>
      </button>
      {open && (
        <div className="shared-report-issue-body">
          <div className="shared-report-issue-field"><span>Problem</span><p>{issue.problem}</p></div>
          <div className="shared-report-issue-field"><span>Cause</span><p>{issue.cause}</p></div>
          <div className="shared-report-issue-field"><span>Impact</span><p>{issue.impact}</p></div>
          <div className="shared-report-issue-field"><span>Suggested Fix</span><p>{issue.suggestedFix}</p></div>
          {issue.url && <div className="shared-report-issue-field"><span>URL</span><p className="mono">{issue.url}</p></div>}
          {issue.selector && <div className="shared-report-issue-field"><span>Selector</span><p className="mono">{issue.selector}</p></div>}
        </div>
      )}
    </div>
  );
}

/**
 * /reports/share/:token — public, read-only, reachable whether or not the
 * visitor is signed in (see App.tsx's path-based bypass, modeled directly
 * on /invitations/:token). No edit/delete/repository/workspace/admin/
 * account controls of any kind — only what LensReport itself carries.
 */
export function SharedReportPage() {
  const { token = '' } = useParams<{ token: string }>();
  const [state, setState] = useState<ViewState>('loading');
  const [report, setReport] = useState<LensReport | null>(null);

  useEffect(() => {
    fetchSharedReport(token)
      .then((res) => {
        setReport(res);
        setState('ready');
      })
      .catch((err) => {
        setState(err instanceof ApiRequestError && err.code === 'REPORT_SHARE_NOT_FOUND' ? 'not-found' : 'error');
      });
  }, [token]);

  return (
    <div className="shared-report-page">
      <header className="shared-report-topbar">
        <OrigamiLensIcon size={28} />
        <span className="shared-report-brand-name">Origami Lens</span>
      </header>

      <main className="shared-report-content">
        {state === 'loading' && <p className="page-subtitle">Loading report…</p>}
        {state === 'not-found' && (
          <div className="shared-report-empty">
            <h1>This link is no longer available</h1>
            <p className="page-subtitle">It may have been disabled by its owner, or the link is incorrect.</p>
          </div>
        )}
        {state === 'error' && (
          <div className="shared-report-empty">
            <h1>Something went wrong</h1>
            <p className="page-subtitle">Could not load this report. Please try again later.</p>
          </div>
        )}
        {state === 'ready' && report && <ReportBody report={report} />}
      </main>

      <footer className="shared-report-footer">Generated by Origami Lens</footer>
    </div>
  );
}

function ReportBody({ report }: { report: LensReport }) {
  const ready = report.reportStatus === 'COMPLETED' || report.reportStatus === 'COMPLETED_WITH_WARNINGS';
  const scannedLabel = report.scannedAt
    ? new Date(report.scannedAt).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })
    : null;

  return (
    <>
      <div className="shared-report-hero">
        <h1>Website Health Report</h1>
        <div className="shared-report-url">{hostnameOf(report.url)}</div>
        {scannedLabel && <div className="shared-report-scanned">Scanned {scannedLabel}</div>}
      </div>

      {!ready ? (
        <div className="shared-report-empty">
          <h2>This scan did not complete successfully</h2>
          <p className="page-subtitle">Status: {report.reportStatus}. No health score or issues are available for this report.</p>
        </div>
      ) : (
        <>
          <div className="shared-report-score-row">
            <AnimatedScoreRing
              score={report.healthScore!}
              tier={report.healthScore! >= 75 ? 'good' : report.healthScore! >= 60 ? 'fair' : 'poor'}
              statusLabel="Health Score"
              ariaLabel={`Health score ${report.healthScore} out of 100`}
            />

            <ul className="shared-report-category-list">
              {report.categories &&
                (Object.entries(report.categories) as [IssueCategory, number][]).map(([key, score]) => (
                  <li key={key} className="shared-report-category-row">
                    <span className="shared-report-category-name">{CATEGORY_LABEL[key]}</span>
                    <AnimatedProgressBar
                      percent={score}
                      dataKey={key}
                      trackClassName="category-progress-track"
                      fillClassName="category-progress-fill"
                    />
                    <span className="shared-report-category-score">{score}</span>
                  </li>
                ))}
            </ul>
          </div>

          <div className="issue-summary-cards shared-report-summary-cards">
            <div className="summary-card critical"><span className="count">{report.summary.critical}</span><span className="label">Critical</span></div>
            <div className="summary-card high"><span className="count">{report.summary.high}</span><span className="label">High</span></div>
            <div className="summary-card medium"><span className="count">{report.summary.medium}</span><span className="label">Medium</span></div>
            <div className="summary-card low"><span className="count">{report.summary.low}</span><span className="label">Low</span></div>
          </div>

          {report.issues.length > 0 && (
            <section className="shared-report-issues">
              <h2>Issues</h2>
              {report.issues.map((issue) => <IssueCard key={issue.id} issue={issue} />)}
            </section>
          )}
        </>
      )}
    </>
  );
}
